services:
  ats-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_PUBLIC_URL=http://localhost:3000
        - REACT_APP_API_URL=http://localhost:3000
    container_name: ats_fe
    restart: unless-stopped
    init: true
    environment:
      REACT_APP_PUBLIC_URL: http://localhost:3000
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:172.17.0.1"